package com.hugootoch.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TurmaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurmaAllPropertiesEquals(Turma expected, Turma actual) {
        assertTurmaAutoGeneratedPropertiesEquals(expected, actual);
        assertTurmaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurmaAllUpdatablePropertiesEquals(Turma expected, Turma actual) {
        assertTurmaUpdatableFieldsEquals(expected, actual);
        assertTurmaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurmaAutoGeneratedPropertiesEquals(Turma expected, Turma actual) {
        assertThat(actual)
            .as("Verify Turma auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurmaUpdatableFieldsEquals(Turma expected, Turma actual) {
        assertThat(actual)
            .as("Verify Turma relevant properties")
            .satisfies(a -> assertThat(a.getNomeTurma()).as("check nomeTurma").isEqualTo(expected.getNomeTurma()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurmaUpdatableRelationshipsEquals(Turma expected, Turma actual) {
        assertThat(actual)
            .as("Verify Turma relationships")
            .satisfies(a -> assertThat(a.getProfessors()).as("check professors").isEqualTo(expected.getProfessors()));
    }
}
